from app import app, db, District

@app.cli.command("add_districts")
def add_district():
    """Add districts by default."""

    district = District.query.get(28)

    if district is None: 
        me = District(code=1, name="Raffles Place, Cecil, Marina, People's Park", zip='01')
        db.session.add(me)
        db.session.commit()
        me = District(code=2, name='Anson, Tanjong Pagar', zip='07')
        db.session.add(me)
        db.session.commit()
        me = District(code=3, name='Queenstown, Tiong Bahru', zip='14')
        db.session.add(me)
        db.session.commit()
        me = District(code=4, name='Telok Blangah, Harbourfront', zip='09')
        db.session.add(me)
        db.session.commit()
        me = District(code=5, name='Pasir Panjang, Hong Leong Garden, Clementi New Town', zip='11')
        db.session.add(me)
        db.session.commit()
        me = District(code=6, name='High Street, Beach Road (part)', zip='17')
        db.session.add(me)
        db.session.commit()
        me = District(code=7, name='Middle Road, Golden Mile', zip='18')
        db.session.add(me)
        db.session.commit()
        me = District(code=8, name='Little India', zip='20')
        db.session.add(me)
        db.session.commit()
        me = District(code=9, name='Orchard, Cairnhill, River Valley', zip='22')
        db.session.add(me)
        db.session.commit()
        me = District(code=10,name= 'Ardmore, Bukit Timah, Holland Road, Tanglin', zip='24')
        db.session.add(me)
        db.session.commit()
        me = District(code=11,name= 'Watten Estate, Novena, Thomson', zip='28')
        db.session.add(me)
        db.session.commit()
        me = District(code=12,name= 'Balestier, Toa Payoh, Serangoon', zip='31')
        db.session.add(me)
        db.session.commit()
        me = District(code=13,name= 'Macpherson, Braddell', zip='34')
        db.session.add(me)
        db.session.commit()
        me = District(code=14,name= 'Geylang, Eunos', zip='38')
        db.session.add(me)
        db.session.commit()
        me = District(code=15,name= 'Katong, Joo Chiat, Amber Road', zip='42')
        db.session.add(me)
        db.session.commit()
        me = District(code=16,name= 'Bedok, Upper East Coast, Eastwood, Kew Drive', zip='46')
        db.session.add(me)
        db.session.commit()
        me = District(code=17,name= 'Loyang, Changi', zip='49')
        db.session.add(me)
        db.session.commit()
        me = District(code=18,name= 'Tampines, Pasir Ris', zip='51')
        db.session.add(me)
        db.session.commit()
        me = District(code=19,name= 'Serangoon Garden, Hougang, Ponggol', zip='53')
        db.session.add(me)
        db.session.commit()
        me = District(code=20,name= 'Bishan, Ang Mo Kio', zip='56')
        db.session.add(me)
        db.session.commit()
        me = District(code=21,name= 'Upper Bukit Timah, Clementi Park, Ulu Pandan', zip='58')
        db.session.add(me)
        db.session.commit()
        me = District(code=22,name= 'Jurong', zip='60')
        db.session.add(me)
        db.session.commit()
        me = District(code=23,name= 'Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang', zip='65')
        db.session.add(me)
        db.session.commit()
        me = District(code=24,name= 'Lim Chu Kang, Tengah', zip='69')
        db.session.add(me)
        db.session.commit()
        me = District(code=25,name= 'Kranji, Woodgrove', zip='72')
        db.session.add(me)
        db.session.commit()
        me = District(code=26,name= 'Upper Thomson, Springleaf', zip='77')
        db.session.add(me)
        db.session.commit()
        me = District(code=27,name= 'Yishun, Sembawang', zip='75')
        db.session.add(me)
        db.session.commit()
        me = District(code=28,name= 'Seletar', zip='79')
        db.session.add(me)
        db.session.commit()

        print('Insertion done..')

        return 

    print('Already inserted...')

    return 

    